### ISSUE TITLE
2 issues - Get file and mirroring

### ISSUE THREAD

**Issue by xScylez** [strawb3rryx7/LLSimpleCamera-Swift-Example#1]
1. How can I get the picture/video after capture and for example save it, or upload it to for example parse.com?

2. When taking photo it mirrors the image, but if I change first to rear cam, and then back to front cam, it does not mirrors image.. Can you please take a look at this?

**Comment by strawb3rryx7** [comment]
I'll update in a few hours. Stay tuned. 😋

**Comment by xScylez** [comment]
Yay!???

Sent from my iPhone

On 09 May 2016, at 15:56, Batuhan Saka <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll update in a few hours. Stay tuned. ?

-

**Comment by xScylez** [comment]
Yay! 😄 Can't wait for it!

**Comment by strawb3rryx7** [comment]
I'll share when i available. I'm currently not in my home.

**Comment by xScylez** [comment]
Oh, OK. I'll be waiting.

Sent from my iPhone

On 10 May 2016, at 17:51, Batuhan Saka <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll share when i available. I'm currently not in my home.

-

**Comment by xScylez** [comment]
@strawb3rryx7 When do you think you will be able to do it? Sorry for nagging 😁

**Comment by strawb3rryx7** [comment]
Hey again, Contact to me on Skype: strawb3rryx7
