### ISSUE TITLE
Upload video to server

### ISSUE THREAD

**Issue by xScylez** [strawb3rryx7/LLSimpleCamera-Swift-Example#2]
I have a problem.

When I do `print("Video URL: \(self.videoUrl.description)")` i get this in the output:

Video URL: `file:///var/mobile/Containers/Data/Application/92BDA035-131C-4FD2-A176-25F77C1D295B/Documents/video.mp4`
I am using this to upload the file to the server:

```
func uploadVideo(){
        let currentUploads = PFObject(className: "myClassOne")
        currentUploads.saveInBackgroundWithBlock({ (success: Bool, error: NSError?) -> Void in
            if error == nil{
                //**Success saving, now save video.**//

                currentUploads["userFile"] = try! PFFile(name: "video.mp4", contentsAtPath: self.videoUrl.description)
                currentUploads.saveInBackgroundWithBlock({ (success: Bool, error: NSError?) -> Void in
                    if error == nil{
                        // Take user home
                        print("Successfully uploaded")
                        })
                    }
                    else{
                        print(error, terminator: "")
                    }
                })
            }
            else{
                print(error, terminator: "")
            }
        })
    }
```
I get this error:

> fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=4 "Failed to create PFFile at path 'file:///var/mobile/Containers/Data/Application/92BDA035-131C-4FD2-A176-25F77C1D295B/Documents/video.mp4': file does not exist." UserInfo={NSLocalizedDescription=Failed to create PFFile at path 'file:///var/mobile/Containers/Data/Application/92BDA035-131C-4FD2-A176-25F77C1D295B/Documents/video.mp4': file does not exist.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.1/src/swift/stdlib/public/core/ErrorType.swift, line 54

What is wrong? Why I get “file does not exist” when I successfully get the url from println? Any ideas/suggestions?

**Comment by strawb3rryx7** [comment]
Issue is solved. 👍

**Comment by xScylez** [comment]
He helped me in team viewer. Fix:

func uploadVideo(){
        if let path = videoUrl.path {
            let currentUploads = PFObject(className: "NorgeStory")
            currentUploads.saveInBackgroundWithBlock({ (success: Bool, error: NSError?) -> Void in
                if error == nil{
                    //**Success saving, now save video.**//
                    
                    currentUploads["userFile"] = try! PFFile(name: "video.mp4", contentsAtPath: path)
                    currentUploads.saveInBackgroundWithBlock({ (success: Bool, error: NSError?) -> Void in
                        if error == nil{
                            // Take user home
                            print("Successfully uploaded")
                        }
                        else{
                            print(error, terminator: "")
                        }
                    })
                }
                else{
                    print(error, terminator: "")
                }
            })
        }
    }
