### ISSUE TITLE
Getting nil.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [strawb3rryx7/LLSimpleCamera-Swift-Example#6]
```
    @IBOutlet weak var snapButton: UIButton!

    @IBOutlet weak var switchButton: UIButton!

    @IBOutlet weak var flashButton: UIButton!

```
I have taken UIButton object from `storyboard`.
At run time it showing me nil `fatal error: unexpectedly found nil while unwrapping an Optional value` at here

`snapButton.clipsToBounds = true`

It is running fine when the `UIButton` object taken programmatically like, 
```
var snapButton = UIButton()
var switchButton = UIButton()
var flashButton = UIButton()
```

what's so problem with `IBOutlet`?

**Comment by strawb3rryx7** [comment]
Did you make connections with IBOutlet & Button on the storyboard ?

**Comment by Rashesh-Bosamiya** [comment]
yes
