### ISSUE TITLE
AVFoundation video upload to server issue - Swift 3

### ISSUE THREAD

**Issue by sathamkhussain** [strawb3rryx7/LLSimpleCamera-Swift-Example#7]
With LLSImpleCamera am recording the video and uploading to server, server always return 500 Internal server error. So I tried by uploading some dummy video(mp4) and it's uploading successfully. When I converted the video to NSData, then I print NSData it shows some kind of weird values. Any help?

**Comment by strawb3rryx7** [comment]
Hey,

Internal Server Error based on your server side. It's not depend LLSimpleCamera.
