### ISSUE TITLE
Project is Using Old Swift Syntax

### ISSUE THREAD

**Issue by Rohanv23** [strawb3rryx7/LLSimpleCamera-Swift-Example#8]
The project needs to be updated to the current swift syntax, swift 3.

**Comment by strawb3rryx7** [comment]
Yes, I am aware of this, but I have not much time yet. I'll update this project syntax Swift 3 in this week.

Thanks for your message.

**Comment by Rohanv23** [comment]
I had already begun to convert the project myself in my app, so if you would like I could send you some of the code I converted.It wasn’t too hard to do though.

Let me know.

**Comment by strawb3rryx7** [comment]
I created new repository. If you want, you can look it. https://github.com/strawb3rryx7/LLSimpleCamera-Swift3-Example
